export const books66 = [
    [ 'Genesis', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Exodus', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Leviticus', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Numbers', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Deuteronomy', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Joshua', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Judges', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Ruth', false, [ false, false, false, false ] ],
    [ '1 Samuel', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '2 Samuel', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '1 Kings', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '2 Kings', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '1 Chronicles', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '2 Chronicles', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Ezra', false, [ false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Nehemiah', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Esther', false, [ false, false, false, false, false, false, false, false, false, false] ],
    [ 'Job', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Psalms', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false] ],
    [ 'Proverbs', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Ecclesiastes', false, [ false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Song of Solomon', false, [ false, false, false, false, false, false, false, false ] ],
    [ 'Isaiah', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Jeremiah', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Lamentations', false, [ false, false, false, false, false ] ],
    [ 'Ezekiel', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Daniel', false, [ false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Hosea', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false] ],
    [ 'Joel', false, [ false, false, false ] ],
    [ 'Amos', false, [ false, false, false, false, false, false, false, false, false ] ],
    [ 'Obadiah', false, [ false ] ],
    [ 'Jonah', false, [ false, false, false, false ] ],
    [ 'Micah', false, [ false, false, false, false, false, false, false ] ],
    [ 'Nahum', false, [ false, false, false ] ],
    [ 'Habakkuk', false, [ false, false, false ] ],
    [ 'Zephaniah', false, [ false, false, false ] ],
    [ 'Haggai', false, [ false, false ] ],
    [ 'Zechariah', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Malachi', false, [ false, false, false, false] ],
    [ 'Mathew', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Mark', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Luke', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'John', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Acts', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Romans', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '1 Corinthians', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ '2 Corinthians', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'Galations', false, [ false, false, false, false, false, false ] ],
    [ 'Ephesians', false, [ false, false, false, false, false, false ] ],
    [ 'Philippians', false, [ false, false, false, false ] ],
    [ 'Colossians', false, [ false, false, false, false ] ],
    [ '1 Thessalonians', false, [ false, false, false, false, false ] ],
    [ '2 Thessalonians', false, [ false, false, false ] ],
    [ '1 Timothy', false, [ false, false, false, false, false, false ] ],
    [ '2 Timothy', false, [ false, false, false, false ] ],
    [ 'Titus', false, [ false, false, false ] ],
    [ 'Philemon', false, [ false ] ],
    [ 'Hebrews', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false ] ],
    [ 'James', false, [ false, false, false, false, false ] ],
    [ '1 Peter', false, [ false, false, false, false, false ] ],
    [ '2 Peter', false, [ false, false, false ] ],
    [ '1 John', false, [ false, false, false, false, false ] ],
    [ '2 John', false, [ false ] ],
    [ '3 John', false, [ false ] ],
    [ 'Jude', false, [ false ] ],
    [ 'Revelation', false, [ false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false ] ] 
  ]

export const books66Old = [ 
    [ 'Genesis', false ],
    [ 'Exodus', false ],
    [ 'Leviticus', false ],
    [ 'Numbers', false ],
    [ 'Deuteronomy', false ],
    [ 'Joshua', false ],
    [ 'Judges', false ],
    [ 'Ruth', false ],
    [ '1 Samuel', false ],
    [ '2 Samuel', false ],
    [ '1 Kings', false ],
    [ '2 Kings', false ],
    [ '1 Chronicles', false ],
    [ '2 Chronicles', false ],
    [ 'Ezra', false ],
    [ 'Nehemiah', false ],
    [ 'Esther', false ],
    [ 'Job', false ],
    [ 'Psalms', false ],
    [ 'Proverbs', false ],
    [ 'Ecclesiastes', false ],
    [ 'Song of Solomon', false ],
    [ 'Isaiah', false ],
    [ 'Jeremiah', false ],
    [ 'Lamentations', false ],
    [ 'Ezekiel', false ],
    [ 'Daniel', false ],
    [ 'Hosea', false ],
    [ 'Joel', false ],
    [ 'Amos', false ],
    [ 'Obadiah', false ],
    [ 'Jonah', false ],
    [ 'Micah', false ],
    [ 'Nahum', false ],
    [ 'Habakkuk', false ],
    [ 'Zephaniah', false ],
    [ 'Haggai', false ],
    [ 'Zechariah', false ],
    [ 'Malachi', false ],
    [ 'Mathew', false ],
    [ 'Mark', false ],
    [ 'Luke', false ],
    [ 'John', false ],
    [ 'Acts', false ],
    [ 'Romans', false ],
    [ '1 Corinthians', false ],
    [ '2 Corinthians', false ],
    [ 'Galations', false ],
    [ 'Ephesians', false ],
    [ 'Philippians', false ],
    [ 'Colossians', false ],
    [ '1 Thessalonians', false ],
    [ '2 Thessalonians', false ],
    [ '1 Timothy', false ],
    [ '2 Timothy', false ],
    [ 'Titus', false ],
    [ 'Philemon', false ],
    [ 'Hebrews', false ],
    [ 'James', false ],
    [ '1 Peter', false ],
    [ '2 Peter', false ],
    [ '1 John', false ],
    [ '2 John', false ],
    [ '3 John', false ],
    [ 'Jude', false ],
    [ 'Revelation', false ] 
  ]

  export const books66True = [
    [ 'Genesis', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Exodus', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Leviticus', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Numbers', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Deuteronomy', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Joshua', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Judges', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Ruth', false, [ true, true, true, true ] ],
    [ '1 Samuel', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '2 Samuel', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '1 Kings', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '2 Kings', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '1 Chronicles', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '2 Chronicles', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Ezra', false, [ true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Nehemiah', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Esther', false, [ true, true, true, true, true, true, true, true, true, true] ],
    [ 'Job', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Psalms', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true] ],
    [ 'Proverbs', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Ecclesiastes', false, [ true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Song of Solomon', false, [ true, true, true, true, true, true, true, true ] ],
    [ 'Isaiah', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Jeremiah', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Lamentations', false, [ true, true, true, true, true ] ],
    [ 'Ezekiel', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Daniel', false, [ true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Hosea', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true] ],
    [ 'Joel', false, [ true, true, true ] ],
    [ 'Amos', false, [ true, true, true, true, true, true, true, true, true ] ],
    [ 'Obadiah', false, [ true ] ],
    [ 'Jonah', false, [ true, true, true, true ] ],
    [ 'Micah', false, [ true, true, true, true, true, true, true ] ],
    [ 'Nahum', false, [ true, true, true ] ],
    [ 'Habakkuk', false, [ true, true, true ] ],
    [ 'Zephaniah', false, [ true, true, true ] ],
    [ 'Haggai', false, [ true, true ] ],
    [ 'Zechariah', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Malachi', false, [ true, true, true, true] ],
    [ 'Mathew', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Mark', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Luke', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'John', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Acts', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Romans', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '1 Corinthians', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ '2 Corinthians', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'Galations', false, [ true, true, true, true, true, true ] ],
    [ 'Ephesians', false, [ true, true, true, true, true, true ] ],
    [ 'Philippians', false, [ true, true, true, true ] ],
    [ 'Colossians', false, [ true, true, true, true ] ],
    [ '1 Thessalonians', false, [ true, true, true, true, true ] ],
    [ '2 Thessalonians', false, [ true, true, true ] ],
    [ '1 Timothy', false, [ true, true, true, true, true, true ] ],
    [ '2 Timothy', false, [ true, true, true, true ] ],
    [ 'Titus', false, [ true, true, true ] ],
    [ 'Philemon', false, [ true ] ],
    [ 'Hebrews', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true ] ],
    [ 'James', false, [ true, true, true, true, true ] ],
    [ '1 Peter', false, [ true, true, true, true, true ] ],
    [ '2 Peter', false, [ true, true, true ] ],
    [ '1 John', false, [ true, true, true, true, true ] ],
    [ '2 John', false, [ true ] ],
    [ '3 John', false, [ true ] ],
    [ 'Jude', false, [ true ] ],
    [ 'Revelation', false, [ true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true ] ] 
  ]